export const NODES_ALL_REQUESTING = '@@NODES/ALL/REQUESTING';
export const NODES_ALL_SUCCESS = '@@NODES/ALL/SUCCESS';
export const NODES_ALL_ERROR = '@@NODES/ALL/ERROR';

export const NODE_REQUESTING = '@@NODE/REQUESTING';
export const NODE_SUCCESS = '@@NODE/SUCCESS';
export const NODE_ERROR = '@@NODE/ERROR';

export const NODE_POST_REQUESTING = '@@NODE/POST/REQUESTING';
export const NODE_POST_SUCCESS = '@@NODE/POST/SUCCESS';
export const NODE_POST_ERROR = '@@NODE/POST/ERROR';

export const NODE_EDIT_REQUESTING = '@@NODE/EDIT/REQUESTING';
export const NODE_EDIT_SUCCESS = '@@NODE/EDIT/SUCCESS';
export const NODE_EDIT_ERROR = '@@NODE/EDIT/ERROR';

export const NODE_REMOVE_REQUESTING = '@@NODE/REMOVE/REQUESTING';
export const NODE_REMOVE_SUCCESS = '@@NODE/REMOVE/SUCCESS';
export const NODE_REMOVE_ERROR = '@@NODE/REMOVE/ERROR';
