export const AUTHENTICATE_REQUESTING = '@@AUTH/LOGIN/REQUESTING';
export const AUTHENTICATE_SUCCESS = '@@AUTH/LOGIN/SUCCESS';
export const AUTHENTICATE_ERROR = '@@AUTH/LOGIN/ERROR';

export const SIGNUP_REQUESTING = '@@USER/SIGNUP/REQUESTING';
export const SIGNUP_SUCCESS = '@@USER/SIGNUP/SUCCESS';
export const SIGNUP_ERROR = '@@USER/SIGNUP/ERROR';

export const LOGOUT_REQUESTING = '@@USER/LOGOUT/REQUESTING';
export const LOGOUT_SUCCESS = '@@USER/LOGOUT/SUCCESS';
export const LOGOUT_ERROR = '@@USER/LOGOUT/ERROR';
